# Generated by Django 5.2.8 on 2025-11-20 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Марка автобуса')),
                ('fuel_consumption', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Витрати пального на 100 км')),
                ('seats_count', models.PositiveIntegerField(verbose_name='Кількість місць')),
            ],
            options={
                'verbose_name': 'Марка автобуса',
                'verbose_name_plural': 'Марки автобусів',
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва пункту прибуття')),
            ],
            options={
                'verbose_name': 'Пункт прибуття',
                'verbose_name_plural': 'Пункти прибуття',
            },
        ),
        migrations.CreateModel(
            name='FuelPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ціна пального')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
            ],
            options={
                'verbose_name': 'Ціна пального',
                'verbose_name_plural': 'Ціни пального',
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Номер автобуса')),
                ('bus_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_station.busmodel', verbose_name='Марка автобуса')),
            ],
            options={
                'verbose_name': 'Автобус',
                'verbose_name_plural': 'Автобуси',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Номер рейсу')),
                ('tariff', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Тариф рейсу')),
                ('days_of_week', models.CharField(max_length=50, verbose_name='Дні тижня виїзду')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Відстань (км)')),
                ('departure_time', models.TimeField(verbose_name='Час відправлення')),
                ('arrival_time', models.TimeField(verbose_name='Час прибуття')),
                ('bus_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_station.busmodel', verbose_name='Марка автобуса')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_station.destination', verbose_name='Пункт прибуття')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршрути',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата виїзду')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_station.bus', verbose_name='Автобус')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_station.route', verbose_name='Маршрут')),
            ],
            options={
                'verbose_name': 'Рейс',
                'verbose_name_plural': 'Рейси',
                'unique_together': {('route', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=20, unique=True, verbose_name='№ квитка')),
                ('seat_number', models.PositiveIntegerField(verbose_name='№ місця')),
                ('status', models.CharField(choices=[('booked', 'Заброньовано'), ('sold', 'Продано'), ('cancelled', 'Скасовано')], default='booked', max_length=10, verbose_name='Статус')),
                ('booking_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата та час бронювання')),
                ('sold_time', models.DateTimeField(blank=True, null=True, verbose_name='Дата та час продажу')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума, сплачена за квиток')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_station.trip', verbose_name='Рейс')),
            ],
            options={
                'verbose_name': 'Квиток',
                'verbose_name_plural': 'Квитки',
            },
        ),
    ]
