# Generated by Django 5.2.8 on 2025-12-14 18:25

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('bus_station', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION decrease_free_seats()
            RETURNS TRIGGER AS $$
            BEGIN
                IF (SELECT free_seats FROM trip WHERE id = NEW.trip_id) <= 0 THEN
                    RAISE EXCEPTION 'No free seats available for this trip';
                END IF;

                UPDATE trip
                SET free_seats = free_seats - 1
                WHERE id = NEW.trip_id;

                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER trg_decrease_free_seats
            BEFORE INSERT ON ticket
            FOR EACH ROW
            EXECUTE FUNCTION decrease_free_seats();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS trg_decrease_free_seats ON ticket;
            DROP FUNCTION IF EXISTS decrease_free_seats();
            """
        )
    ]

